# Generated by Django 2.2.10 on 2020-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200223_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_Of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Ot', 'Other')], default='M', max_length=10),
        ),
    ]
