# Generated by Django 2.2.10 on 2020-02-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffctccallotment',
            name='class_counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_counsellor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffctccallotment',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffctccallotment',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department'),
        ),
    ]
