# Generated by Django 2.2.10 on 2020-02-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200223_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffctccallotment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Term'),
        ),
    ]
