# Generated by Django 2.2.10 on 2020-02-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200223_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffctccallotment',
            old_name='term',
            new_name='term_id',
        ),
    ]
