# Generated by Django 2.2.10 on 2020-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='sem',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_id',
            field=models.IntegerField(unique=True),
        ),
    ]
